# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import EdigRPC_pb2 as EdigRPC__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in EdigRPC_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EdigRPCStub:
    """/////////////////////////////////////////////////////////////////////////////
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Controller_CreateDevice = channel.unary_unary(
                '/EdigRPC.gen.EdigRPC/Controller_CreateDevice',
                request_serializer=EdigRPC__pb2.Controller_CreateDeviceRequest.SerializeToString,
                response_deserializer=EdigRPC__pb2.Controller_CreateDeviceResponse.FromString,
                _registered_method=True)
        self.DeviceManager_GetDevices = channel.unary_unary(
                '/EdigRPC.gen.EdigRPC/DeviceManager_GetDevices',
                request_serializer=EdigRPC__pb2.DeviceManager_GetDevicesRequest.SerializeToString,
                response_deserializer=EdigRPC__pb2.DeviceManager_GetDevicesResponse.FromString,
                _registered_method=True)
        self.DeviceManager_DeviceAttach = channel.unary_stream(
                '/EdigRPC.gen.EdigRPC/DeviceManager_DeviceAttach',
                request_serializer=EdigRPC__pb2.DeviceManager_DeviceAttachRequest.SerializeToString,
                response_deserializer=EdigRPC__pb2.DeviceManager_DeviceAttachResponse.FromString,
                _registered_method=True)
        self.DeviceManager_DeviceDetach = channel.unary_stream(
                '/EdigRPC.gen.EdigRPC/DeviceManager_DeviceDetach',
                request_serializer=EdigRPC__pb2.DeviceManager_DeviceDetachRequest.SerializeToString,
                response_deserializer=EdigRPC__pb2.DeviceManager_DeviceDetachResponse.FromString,
                _registered_method=True)
        self.Amplifier_Dispose = channel.unary_unary(
                '/EdigRPC.gen.EdigRPC/Amplifier_Dispose',
                request_serializer=EdigRPC__pb2.Amplifier_DisposeRequest.SerializeToString,
                response_deserializer=EdigRPC__pb2.Amplifier_DisposeResponse.FromString,
                _registered_method=True)
        self.Amplifier_GetDeviceInformation = channel.unary_unary(
                '/EdigRPC.gen.EdigRPC/Amplifier_GetDeviceInformation',
                request_serializer=EdigRPC__pb2.Amplifier_GetDeviceInformationRequest.SerializeToString,
                response_deserializer=EdigRPC__pb2.Amplifier_GetDeviceInformationResponse.FromString,
                _registered_method=True)
        self.Amplifier_GetDeviceParameters = channel.unary_unary(
                '/EdigRPC.gen.EdigRPC/Amplifier_GetDeviceParameters',
                request_serializer=EdigRPC__pb2.Amplifier_GetDeviceParametersRequest.SerializeToString,
                response_deserializer=EdigRPC__pb2.Amplifier_GetDeviceParametersResponse.FromString,
                _registered_method=True)
        self.Amplifier_GetChannelsAvailable = channel.unary_unary(
                '/EdigRPC.gen.EdigRPC/Amplifier_GetChannelsAvailable',
                request_serializer=EdigRPC__pb2.Amplifier_GetChannelsAvailableRequest.SerializeToString,
                response_deserializer=EdigRPC__pb2.Amplifier_GetChannelsAvailableResponse.FromString,
                _registered_method=True)
        self.Amplifier_GetSamplingRatesAvailable = channel.unary_unary(
                '/EdigRPC.gen.EdigRPC/Amplifier_GetSamplingRatesAvailable',
                request_serializer=EdigRPC__pb2.Amplifier_GetSamplingRatesAvailableRequest.SerializeToString,
                response_deserializer=EdigRPC__pb2.Amplifier_GetSamplingRatesAvailableResponse.FromString,
                _registered_method=True)
        self.Amplifier_GetModesAvailable = channel.unary_unary(
                '/EdigRPC.gen.EdigRPC/Amplifier_GetModesAvailable',
                request_serializer=EdigRPC__pb2.Amplifier_GetModesAvailableRequest.SerializeToString,
                response_deserializer=EdigRPC__pb2.Amplifier_GetModesAvailableResponse.FromString,
                _registered_method=True)
        self.Amplifier_GetRangesAvailable = channel.unary_unary(
                '/EdigRPC.gen.EdigRPC/Amplifier_GetRangesAvailable',
                request_serializer=EdigRPC__pb2.Amplifier_GetRangesAvailableRequest.SerializeToString,
                response_deserializer=EdigRPC__pb2.Amplifier_GetRangesAvailableResponse.FromString,
                _registered_method=True)
        self.Amplifier_GetMode = channel.unary_unary(
                '/EdigRPC.gen.EdigRPC/Amplifier_GetMode',
                request_serializer=EdigRPC__pb2.Amplifier_GetModeRequest.SerializeToString,
                response_deserializer=EdigRPC__pb2.Amplifier_GetModeResponse.FromString,
                _registered_method=True)
        self.Amplifier_SetMode = channel.unary_unary(
                '/EdigRPC.gen.EdigRPC/Amplifier_SetMode',
                request_serializer=EdigRPC__pb2.Amplifier_SetModeRequest.SerializeToString,
                response_deserializer=EdigRPC__pb2.Amplifier_SetModeResponse.FromString,
                _registered_method=True)
        self.Amplifier_GetFrame = channel.unary_unary(
                '/EdigRPC.gen.EdigRPC/Amplifier_GetFrame',
                request_serializer=EdigRPC__pb2.Amplifier_GetFrameRequest.SerializeToString,
                response_deserializer=EdigRPC__pb2.Amplifier_GetFrameResponse.FromString,
                _registered_method=True)
        self.Amplifier_GetPower = channel.unary_unary(
                '/EdigRPC.gen.EdigRPC/Amplifier_GetPower',
                request_serializer=EdigRPC__pb2.Amplifier_GetPowerRequest.SerializeToString,
                response_deserializer=EdigRPC__pb2.Amplifier_GetPowerResponse.FromString,
                _registered_method=True)
        self.Amplifier_SetOutputTriggerChannels = channel.unary_unary(
                '/EdigRPC.gen.EdigRPC/Amplifier_SetOutputTriggerChannels',
                request_serializer=EdigRPC__pb2.Amplifier_SetOutputTriggerChannelsRequest.SerializeToString,
                response_deserializer=EdigRPC__pb2.Amplifier_SetOutputTriggerChannelsResponse.FromString,
                _registered_method=True)
        self.Amplifier_SetStimulationParameters = channel.unary_unary(
                '/EdigRPC.gen.EdigRPC/Amplifier_SetStimulationParameters',
                request_serializer=EdigRPC__pb2.Amplifier_SetStimulationParametersRequest.SerializeToString,
                response_deserializer=EdigRPC__pb2.Amplifier_SetStimulationParametersResponse.FromString,
                _registered_method=True)
        self.Amplifier_StartOutputTrigger = channel.unary_unary(
                '/EdigRPC.gen.EdigRPC/Amplifier_StartOutputTrigger',
                request_serializer=EdigRPC__pb2.Amplifier_StartOutputTriggerRequest.SerializeToString,
                response_deserializer=EdigRPC__pb2.Amplifier_StartOutputTriggerResponse.FromString,
                _registered_method=True)
        self.Amplifier_StopOutputTrigger = channel.unary_unary(
                '/EdigRPC.gen.EdigRPC/Amplifier_StopOutputTrigger',
                request_serializer=EdigRPC__pb2.Amplifier_StopOutputTriggerRequest.SerializeToString,
                response_deserializer=EdigRPC__pb2.Amplifier_StopOutputTriggerResponse.FromString,
                _registered_method=True)
        self.Amplifier_StartStimulation = channel.unary_unary(
                '/EdigRPC.gen.EdigRPC/Amplifier_StartStimulation',
                request_serializer=EdigRPC__pb2.Amplifier_StartStimulationRequest.SerializeToString,
                response_deserializer=EdigRPC__pb2.Amplifier_StartStimulationResponse.FromString,
                _registered_method=True)
        self.Amplifier_StopStimulation = channel.unary_unary(
                '/EdigRPC.gen.EdigRPC/Amplifier_StopStimulation',
                request_serializer=EdigRPC__pb2.Amplifier_StopStimulationRequest.SerializeToString,
                response_deserializer=EdigRPC__pb2.Amplifier_StopStimulationResponse.FromString,
                _registered_method=True)
        self.Amplifier_NotifyEvent = channel.unary_stream(
                '/EdigRPC.gen.EdigRPC/Amplifier_NotifyEvent',
                request_serializer=EdigRPC__pb2.Amplifier_NotifyEventRequest.SerializeToString,
                response_deserializer=EdigRPC__pb2.Amplifier_NotifyEventResponse.FromString,
                _registered_method=True)
        self.GetState = channel.unary_unary(
                '/EdigRPC.gen.EdigRPC/GetState',
                request_serializer=EdigRPC__pb2.GetStateRequest.SerializeToString,
                response_deserializer=EdigRPC__pb2.GetStateResponse.FromString,
                _registered_method=True)


class EdigRPCServicer:
    """/////////////////////////////////////////////////////////////////////////////
    """

    def Controller_CreateDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeviceManager_GetDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeviceManager_DeviceAttach(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeviceManager_DeviceDetach(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Amplifier_Dispose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Amplifier_GetDeviceInformation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Amplifier_GetDeviceParameters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Amplifier_GetChannelsAvailable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Amplifier_GetSamplingRatesAvailable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Amplifier_GetModesAvailable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Amplifier_GetRangesAvailable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Amplifier_GetMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Amplifier_SetMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Amplifier_GetFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Amplifier_GetPower(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Amplifier_SetOutputTriggerChannels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Amplifier_SetStimulationParameters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Amplifier_StartOutputTrigger(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Amplifier_StopOutputTrigger(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Amplifier_StartStimulation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Amplifier_StopStimulation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Amplifier_NotifyEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EdigRPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Controller_CreateDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.Controller_CreateDevice,
                    request_deserializer=EdigRPC__pb2.Controller_CreateDeviceRequest.FromString,
                    response_serializer=EdigRPC__pb2.Controller_CreateDeviceResponse.SerializeToString,
            ),
            'DeviceManager_GetDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.DeviceManager_GetDevices,
                    request_deserializer=EdigRPC__pb2.DeviceManager_GetDevicesRequest.FromString,
                    response_serializer=EdigRPC__pb2.DeviceManager_GetDevicesResponse.SerializeToString,
            ),
            'DeviceManager_DeviceAttach': grpc.unary_stream_rpc_method_handler(
                    servicer.DeviceManager_DeviceAttach,
                    request_deserializer=EdigRPC__pb2.DeviceManager_DeviceAttachRequest.FromString,
                    response_serializer=EdigRPC__pb2.DeviceManager_DeviceAttachResponse.SerializeToString,
            ),
            'DeviceManager_DeviceDetach': grpc.unary_stream_rpc_method_handler(
                    servicer.DeviceManager_DeviceDetach,
                    request_deserializer=EdigRPC__pb2.DeviceManager_DeviceDetachRequest.FromString,
                    response_serializer=EdigRPC__pb2.DeviceManager_DeviceDetachResponse.SerializeToString,
            ),
            'Amplifier_Dispose': grpc.unary_unary_rpc_method_handler(
                    servicer.Amplifier_Dispose,
                    request_deserializer=EdigRPC__pb2.Amplifier_DisposeRequest.FromString,
                    response_serializer=EdigRPC__pb2.Amplifier_DisposeResponse.SerializeToString,
            ),
            'Amplifier_GetDeviceInformation': grpc.unary_unary_rpc_method_handler(
                    servicer.Amplifier_GetDeviceInformation,
                    request_deserializer=EdigRPC__pb2.Amplifier_GetDeviceInformationRequest.FromString,
                    response_serializer=EdigRPC__pb2.Amplifier_GetDeviceInformationResponse.SerializeToString,
            ),
            'Amplifier_GetDeviceParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.Amplifier_GetDeviceParameters,
                    request_deserializer=EdigRPC__pb2.Amplifier_GetDeviceParametersRequest.FromString,
                    response_serializer=EdigRPC__pb2.Amplifier_GetDeviceParametersResponse.SerializeToString,
            ),
            'Amplifier_GetChannelsAvailable': grpc.unary_unary_rpc_method_handler(
                    servicer.Amplifier_GetChannelsAvailable,
                    request_deserializer=EdigRPC__pb2.Amplifier_GetChannelsAvailableRequest.FromString,
                    response_serializer=EdigRPC__pb2.Amplifier_GetChannelsAvailableResponse.SerializeToString,
            ),
            'Amplifier_GetSamplingRatesAvailable': grpc.unary_unary_rpc_method_handler(
                    servicer.Amplifier_GetSamplingRatesAvailable,
                    request_deserializer=EdigRPC__pb2.Amplifier_GetSamplingRatesAvailableRequest.FromString,
                    response_serializer=EdigRPC__pb2.Amplifier_GetSamplingRatesAvailableResponse.SerializeToString,
            ),
            'Amplifier_GetModesAvailable': grpc.unary_unary_rpc_method_handler(
                    servicer.Amplifier_GetModesAvailable,
                    request_deserializer=EdigRPC__pb2.Amplifier_GetModesAvailableRequest.FromString,
                    response_serializer=EdigRPC__pb2.Amplifier_GetModesAvailableResponse.SerializeToString,
            ),
            'Amplifier_GetRangesAvailable': grpc.unary_unary_rpc_method_handler(
                    servicer.Amplifier_GetRangesAvailable,
                    request_deserializer=EdigRPC__pb2.Amplifier_GetRangesAvailableRequest.FromString,
                    response_serializer=EdigRPC__pb2.Amplifier_GetRangesAvailableResponse.SerializeToString,
            ),
            'Amplifier_GetMode': grpc.unary_unary_rpc_method_handler(
                    servicer.Amplifier_GetMode,
                    request_deserializer=EdigRPC__pb2.Amplifier_GetModeRequest.FromString,
                    response_serializer=EdigRPC__pb2.Amplifier_GetModeResponse.SerializeToString,
            ),
            'Amplifier_SetMode': grpc.unary_unary_rpc_method_handler(
                    servicer.Amplifier_SetMode,
                    request_deserializer=EdigRPC__pb2.Amplifier_SetModeRequest.FromString,
                    response_serializer=EdigRPC__pb2.Amplifier_SetModeResponse.SerializeToString,
            ),
            'Amplifier_GetFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.Amplifier_GetFrame,
                    request_deserializer=EdigRPC__pb2.Amplifier_GetFrameRequest.FromString,
                    response_serializer=EdigRPC__pb2.Amplifier_GetFrameResponse.SerializeToString,
            ),
            'Amplifier_GetPower': grpc.unary_unary_rpc_method_handler(
                    servicer.Amplifier_GetPower,
                    request_deserializer=EdigRPC__pb2.Amplifier_GetPowerRequest.FromString,
                    response_serializer=EdigRPC__pb2.Amplifier_GetPowerResponse.SerializeToString,
            ),
            'Amplifier_SetOutputTriggerChannels': grpc.unary_unary_rpc_method_handler(
                    servicer.Amplifier_SetOutputTriggerChannels,
                    request_deserializer=EdigRPC__pb2.Amplifier_SetOutputTriggerChannelsRequest.FromString,
                    response_serializer=EdigRPC__pb2.Amplifier_SetOutputTriggerChannelsResponse.SerializeToString,
            ),
            'Amplifier_SetStimulationParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.Amplifier_SetStimulationParameters,
                    request_deserializer=EdigRPC__pb2.Amplifier_SetStimulationParametersRequest.FromString,
                    response_serializer=EdigRPC__pb2.Amplifier_SetStimulationParametersResponse.SerializeToString,
            ),
            'Amplifier_StartOutputTrigger': grpc.unary_unary_rpc_method_handler(
                    servicer.Amplifier_StartOutputTrigger,
                    request_deserializer=EdigRPC__pb2.Amplifier_StartOutputTriggerRequest.FromString,
                    response_serializer=EdigRPC__pb2.Amplifier_StartOutputTriggerResponse.SerializeToString,
            ),
            'Amplifier_StopOutputTrigger': grpc.unary_unary_rpc_method_handler(
                    servicer.Amplifier_StopOutputTrigger,
                    request_deserializer=EdigRPC__pb2.Amplifier_StopOutputTriggerRequest.FromString,
                    response_serializer=EdigRPC__pb2.Amplifier_StopOutputTriggerResponse.SerializeToString,
            ),
            'Amplifier_StartStimulation': grpc.unary_unary_rpc_method_handler(
                    servicer.Amplifier_StartStimulation,
                    request_deserializer=EdigRPC__pb2.Amplifier_StartStimulationRequest.FromString,
                    response_serializer=EdigRPC__pb2.Amplifier_StartStimulationResponse.SerializeToString,
            ),
            'Amplifier_StopStimulation': grpc.unary_unary_rpc_method_handler(
                    servicer.Amplifier_StopStimulation,
                    request_deserializer=EdigRPC__pb2.Amplifier_StopStimulationRequest.FromString,
                    response_serializer=EdigRPC__pb2.Amplifier_StopStimulationResponse.SerializeToString,
            ),
            'Amplifier_NotifyEvent': grpc.unary_stream_rpc_method_handler(
                    servicer.Amplifier_NotifyEvent,
                    request_deserializer=EdigRPC__pb2.Amplifier_NotifyEventRequest.FromString,
                    response_serializer=EdigRPC__pb2.Amplifier_NotifyEventResponse.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=EdigRPC__pb2.GetStateRequest.FromString,
                    response_serializer=EdigRPC__pb2.GetStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'EdigRPC.gen.EdigRPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('EdigRPC.gen.EdigRPC', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EdigRPC:
    """/////////////////////////////////////////////////////////////////////////////
    """

    @staticmethod
    def Controller_CreateDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EdigRPC.gen.EdigRPC/Controller_CreateDevice',
            EdigRPC__pb2.Controller_CreateDeviceRequest.SerializeToString,
            EdigRPC__pb2.Controller_CreateDeviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeviceManager_GetDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EdigRPC.gen.EdigRPC/DeviceManager_GetDevices',
            EdigRPC__pb2.DeviceManager_GetDevicesRequest.SerializeToString,
            EdigRPC__pb2.DeviceManager_GetDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeviceManager_DeviceAttach(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/EdigRPC.gen.EdigRPC/DeviceManager_DeviceAttach',
            EdigRPC__pb2.DeviceManager_DeviceAttachRequest.SerializeToString,
            EdigRPC__pb2.DeviceManager_DeviceAttachResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeviceManager_DeviceDetach(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/EdigRPC.gen.EdigRPC/DeviceManager_DeviceDetach',
            EdigRPC__pb2.DeviceManager_DeviceDetachRequest.SerializeToString,
            EdigRPC__pb2.DeviceManager_DeviceDetachResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Amplifier_Dispose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EdigRPC.gen.EdigRPC/Amplifier_Dispose',
            EdigRPC__pb2.Amplifier_DisposeRequest.SerializeToString,
            EdigRPC__pb2.Amplifier_DisposeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Amplifier_GetDeviceInformation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EdigRPC.gen.EdigRPC/Amplifier_GetDeviceInformation',
            EdigRPC__pb2.Amplifier_GetDeviceInformationRequest.SerializeToString,
            EdigRPC__pb2.Amplifier_GetDeviceInformationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Amplifier_GetDeviceParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EdigRPC.gen.EdigRPC/Amplifier_GetDeviceParameters',
            EdigRPC__pb2.Amplifier_GetDeviceParametersRequest.SerializeToString,
            EdigRPC__pb2.Amplifier_GetDeviceParametersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Amplifier_GetChannelsAvailable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EdigRPC.gen.EdigRPC/Amplifier_GetChannelsAvailable',
            EdigRPC__pb2.Amplifier_GetChannelsAvailableRequest.SerializeToString,
            EdigRPC__pb2.Amplifier_GetChannelsAvailableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Amplifier_GetSamplingRatesAvailable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EdigRPC.gen.EdigRPC/Amplifier_GetSamplingRatesAvailable',
            EdigRPC__pb2.Amplifier_GetSamplingRatesAvailableRequest.SerializeToString,
            EdigRPC__pb2.Amplifier_GetSamplingRatesAvailableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Amplifier_GetModesAvailable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EdigRPC.gen.EdigRPC/Amplifier_GetModesAvailable',
            EdigRPC__pb2.Amplifier_GetModesAvailableRequest.SerializeToString,
            EdigRPC__pb2.Amplifier_GetModesAvailableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Amplifier_GetRangesAvailable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EdigRPC.gen.EdigRPC/Amplifier_GetRangesAvailable',
            EdigRPC__pb2.Amplifier_GetRangesAvailableRequest.SerializeToString,
            EdigRPC__pb2.Amplifier_GetRangesAvailableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Amplifier_GetMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EdigRPC.gen.EdigRPC/Amplifier_GetMode',
            EdigRPC__pb2.Amplifier_GetModeRequest.SerializeToString,
            EdigRPC__pb2.Amplifier_GetModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Amplifier_SetMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EdigRPC.gen.EdigRPC/Amplifier_SetMode',
            EdigRPC__pb2.Amplifier_SetModeRequest.SerializeToString,
            EdigRPC__pb2.Amplifier_SetModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Amplifier_GetFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EdigRPC.gen.EdigRPC/Amplifier_GetFrame',
            EdigRPC__pb2.Amplifier_GetFrameRequest.SerializeToString,
            EdigRPC__pb2.Amplifier_GetFrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Amplifier_GetPower(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EdigRPC.gen.EdigRPC/Amplifier_GetPower',
            EdigRPC__pb2.Amplifier_GetPowerRequest.SerializeToString,
            EdigRPC__pb2.Amplifier_GetPowerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Amplifier_SetOutputTriggerChannels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EdigRPC.gen.EdigRPC/Amplifier_SetOutputTriggerChannels',
            EdigRPC__pb2.Amplifier_SetOutputTriggerChannelsRequest.SerializeToString,
            EdigRPC__pb2.Amplifier_SetOutputTriggerChannelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Amplifier_SetStimulationParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EdigRPC.gen.EdigRPC/Amplifier_SetStimulationParameters',
            EdigRPC__pb2.Amplifier_SetStimulationParametersRequest.SerializeToString,
            EdigRPC__pb2.Amplifier_SetStimulationParametersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Amplifier_StartOutputTrigger(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EdigRPC.gen.EdigRPC/Amplifier_StartOutputTrigger',
            EdigRPC__pb2.Amplifier_StartOutputTriggerRequest.SerializeToString,
            EdigRPC__pb2.Amplifier_StartOutputTriggerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Amplifier_StopOutputTrigger(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EdigRPC.gen.EdigRPC/Amplifier_StopOutputTrigger',
            EdigRPC__pb2.Amplifier_StopOutputTriggerRequest.SerializeToString,
            EdigRPC__pb2.Amplifier_StopOutputTriggerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Amplifier_StartStimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EdigRPC.gen.EdigRPC/Amplifier_StartStimulation',
            EdigRPC__pb2.Amplifier_StartStimulationRequest.SerializeToString,
            EdigRPC__pb2.Amplifier_StartStimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Amplifier_StopStimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EdigRPC.gen.EdigRPC/Amplifier_StopStimulation',
            EdigRPC__pb2.Amplifier_StopStimulationRequest.SerializeToString,
            EdigRPC__pb2.Amplifier_StopStimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Amplifier_NotifyEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/EdigRPC.gen.EdigRPC/Amplifier_NotifyEvent',
            EdigRPC__pb2.Amplifier_NotifyEventRequest.SerializeToString,
            EdigRPC__pb2.Amplifier_NotifyEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EdigRPC.gen.EdigRPC/GetState',
            EdigRPC__pb2.GetStateRequest.SerializeToString,
            EdigRPC__pb2.GetStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
